### ISSUE TITLE
IBM.csv and IBM_O.csv files are missing

### ISSUE THREAD

**Issue by rezacsedu** [prnicolas/ScalaML_2nd_Edition#1]
Hi @prnicolas,

I did not find the IBM.csv and IBM_O.csv files in this script:
https://github.com/prnicolas/ScalaML_2nd_Edition/blob/master/src/test/scala/org/scalaml/reinforcement/qlearning/QLearningTest.scala 

Any clue?

**Comment by prnicolas** [comment]
This has been corrected on GitHub.
Patrick R. Nicolas 

 

    On Friday, January 5, 2018, 11:09:12 AM PST, Md. Rezaul Karim <notifications@github.com> wrote:  
 
 
Hi @prnicolas,

I did not find the IBM.csv and IBM_O.csv files in this script:
https://github.com/prnicolas/ScalaML_2nd_Edition/blob/master/src/test/scala/org/scalaml/reinforcement/qlearning/QLearningTest.scala

Any clue?
